services:
  - type: web
    name: snake-game
    env: docker
    region: oregon
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: docker build -t snake-game .
    startCommand: docker run -p 10000:10000 snake-game
    healthCheckPath: /
